---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: __DRIVER_NAME__
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - "resource.k8s.io"
    resources:
      - resourceslices
    verbs:
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - "resource.k8s.io"
    resources:
      - resourceclaims
      - deviceclasses
    verbs:
      - get
  - apiGroups:
      - "resource.k.io/v1"
    resources:
      - resourceclaims/status
    verbs:
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: __DRIVER_NAME__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: __DRIVER_NAME__
subjects:
- kind: ServiceAccount
  name: __DRIVER_NAME__
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: __DRIVER_NAME__
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: __DRIVER_NAME__
  namespace: kube-system
  labels:
    tier: node
    app: __DRIVER_NAME__
    k8s-app: __DRIVER_NAME__
spec:
  selector:
    matchLabels:
      app: __DRIVER_NAME__
  template:
    metadata:
      labels:
        tier: node
        app: __DRIVER_NAME__
        k8s-app: __DRIVER_NAME__
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: __DRIVER_NAME__
      containers:
      - name: driver
        args:
        - /__DRIVER_BINARY__
        - --v=4
        image: __DRIVER_IMAGE__:stable
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9177
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/plugins
        - name: plugin-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: nri-plugin
          mountPath: /var/run/nri
        - name: netns
          mountPath: /var/run/netns
          mountPropagation: HostToContainer
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: plugin-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: nri-plugin
        hostPath:
          path: /var/run/nri
      - name: netns
        hostPath:
          path: /var/run/netns
---